### ISSUE TITLE
Link to working example

### ISSUE THREAD

**Issue by michaelhitzker** [htl-perg-2018-19-4bhif/angular-todo-example-michaelhitzker#1]
https://www.michaelhitzker.com/htl/TodoGUI/

If https does not work, you could try http or, if using chrome, press the icon next to the "Add Bookmark icon" and press "load unsafe scripts". It should look like this: ![image](https://user-images.githubusercontent.com/33837887/55027681-23133d00-5006-11e9-88e1-5aa550f34d37.png)
If the API does not work, please let me know. I might have to change the IP of the API then.

**Comment by rstropek** [comment]
Hi @michaelhitzker!

Works perfectly fine 👍. The extra point for Angular Material is yours.

Greetings,
Rainer Stropek.
